# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miotask', '0002_extenduser_random_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='birthday_date',
            field=models.DateField(null=True),
        ),
    ]
